<?php

return [
    'features' => [
        'default_plan' => env('CAPTURE_DEFAULT_PLAN', 'growth'),
        'show_admin_login_links' => (bool) env('CAPTURE_SHOW_ADMIN_LOGIN_LINKS', false),
        'plan_enforcement_enabled' => (bool) env('CAPTURE_PLAN_ENFORCEMENT_ENABLED', true),
        'plan_cache_ttl_seconds' => (int) env('CAPTURE_PLAN_CACHE_TTL_SECONDS', 300),
        'starter_form_limit' => (int) env('CAPTURE_STARTER_FORM_LIMIT', 1),
        'plan_invite_roles' => [
            'starter' => ['viewer'],
            'growth' => ['member', 'viewer'],
            'pro' => ['owner', 'member', 'viewer'],
        ],
        'notes_force_enabled' => (bool) env('CAPTURE_NOTES_FORCE_ENABLED', false),
        'insights_force_enabled' => (bool) env('CAPTURE_INSIGHTS_FORCE_ENABLED', false),
        'insights_allowed_plans' => ['pro'],
        'admin_audit_log_enabled' => (bool) env('ADMIN_AUDIT_LOG_ENABLED', true),
        'enforce_access_context' => (bool) env('CAPTURE_ENFORCE_ACCESS_CONTEXT', false),
        'harden_admin_sessions' => (bool) env('CAPTURE_HARDEN_ADMIN_SESSIONS', true),
        'admin_session_idle_timeout_minutes' => (int) env('CAPTURE_ADMIN_SESSION_IDLE_TIMEOUT_MINUTES', 20),
        'require_form_consent' => (bool) env('CAPTURE_REQUIRE_FORM_CONSENT', false),
        'enforce_form_domain_validation' => (bool) env('CAPTURE_ENFORCE_FORM_DOMAIN_VALIDATION', false),
        'enable_form_success_redirect' => (bool) env('CAPTURE_ENABLE_FORM_SUCCESS_REDIRECT', false),
        'store_submission_request_metadata' => (bool) env('CAPTURE_STORE_SUBMISSION_REQUEST_METADATA', false),
        'audit_metadata_redact_keys' => ['email', 'name', 'subject', 'message', 'content'],
        'enable_form_custom_themes' => (bool) env('CAPTURE_ENABLE_FORM_CUSTOM_THEMES', true),
        'enable_form_custom_fields' => (bool) env('CAPTURE_ENABLE_FORM_CUSTOM_FIELDS', true),
        'enable_form_file_uploads' => (bool) env('CAPTURE_ENABLE_FORM_FILE_UPLOADS', true),
        'enable_form_submission_webhooks' => (bool) env('CAPTURE_ENABLE_FORM_SUBMISSION_WEBHOOKS', true),
        'demo_submission_ttl_minutes' => (int) env('CAPTURE_DEMO_SUBMISSION_TTL_MINUTES', 120),
        'secret_rotation_interval_days' => (int) env('CAPTURE_SECRET_ROTATION_INTERVAL_DAYS', 90),
        'last_secret_rotation_at' => env('CAPTURE_LAST_SECRET_ROTATION_AT'),
        'sso_enabled' => (bool) env('CAPTURE_SSO_ENABLED', false),
        'sso_shared_secret' => env('CAPTURE_SSO_SHARED_SECRET'),
        'sso_signature_ttl_seconds' => (int) env('CAPTURE_SSO_SIGNATURE_TTL_SECONDS', 300),
        'support_contact_email' => env('CAPTURE_SUPPORT_CONTACT_EMAIL', 'support@gracesoft.dev'),
        'default_account_id' => env('CAPTURE_DEFAULT_ACCOUNT_ID', '00000000-0000-0000-0000-000000000001'),
        'consent_policy_version' => env('CAPTURE_CONSENT_POLICY_VERSION', 'v1'),
        'data_retention_days' => (int) env('APP_DATA_RETENTION_DAYS', 365),
        'admin_compliance_plan_gate_enabled' => (bool) env('CAPTURE_ADMIN_COMPLIANCE_PLAN_GATE_ENABLED', false),
        'admin_compliance_allowed_plans' => ['pro'],
        'require_admin_mfa_for_compliance' => (bool) env('CAPTURE_REQUIRE_ADMIN_MFA_FOR_COMPLIANCE', false),
        'require_break_glass_for_sensitive_dsr' => (bool) env('CAPTURE_REQUIRE_BREAK_GLASS_FOR_SENSITIVE_DSR', false),
        'break_glass_default_expiry_minutes' => (int) env('CAPTURE_BREAK_GLASS_DEFAULT_EXPIRY_MINUTES', 30),
        'require_verified_email_for_collaborator_acceptance' => (bool) env('CAPTURE_REQUIRE_VERIFIED_EMAIL_FOR_COLLABORATOR_ACCEPTANCE', false),
        'require_verified_email_for_sensitive_admin_operations' => (bool) env('CAPTURE_REQUIRE_VERIFIED_EMAIL_FOR_SENSITIVE_ADMIN_OPERATIONS', false),
        'verification_block_metrics_enabled' => (bool) env('CAPTURE_VERIFICATION_BLOCK_METRICS_ENABLED', true),
        'admin_access_recertification_days' => (int) env('CAPTURE_ADMIN_ACCESS_RECERTIFICATION_DAYS', 90),
        'collaborator_invite_alert_threshold' => (int) env('CAPTURE_COLLAB_INVITE_ALERT_THRESHOLD', 3),
        'collaborator_invite_alert_window_minutes' => (int) env('CAPTURE_COLLAB_INVITE_ALERT_WINDOW_MINUTES', 30),
    ],
    'admin_authorization' => [
        'default_role' => env('CAPTURE_DEFAULT_ADMIN_ROLE', 'compliance_admin'),
        'role_capabilities' => [
            'compliance_reader' => [
                'compliance.view',
            ],
            'compliance_operator' => [
                'compliance.view',
                'compliance.manage_dsr_status',
                'compliance.break_glass.request',
            ],
            'compliance_admin' => [
                'compliance.view',
                'compliance.view_sensitive',
                'compliance.manage_dsr_status',
                'compliance.process_dsr',
                'compliance.break_glass.request',
                'compliance.break_glass.approve',
                'compliance.recertify_admin_access',
            ],
        ],
    ],
];
